#!/usr/bin/env bash
target="$1"
if ! [ "$target" ]; then
	target="$(find . |grep '[0-9][0-9]*\.bqn'|sort -n|tail -n1)"
fi
function watch() {
	if command -v inotifywait >/dev/null; then
		inotifywait -m -e modify "$@"
	else
		fswatch "$@"
	fi
	
}
( echo ; watch */*.bqn ) | while read; do
	clear
	out="$(bqn "$target")"
	# Find the last answer in the output and
	# copy it to the clipboard.
	<<<"$out" sed '$!d;s/.*:\s*//;s/\s*$//'\
		| xclip -selection clipboard -rmlastnl \
		> /dev/null 2>/dev/null
	echo "$out"
done
